name: Build-Debug

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'src/**'

jobs:
  build:
    name: Build binary
    runs-on: windows-2022
    strategy:
      matrix:
        configuration:
          - Debug

    steps:
      - name: Wait for previous workflows
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out files
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
          lfs: false

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Generate project files
        run: tools/premake5 vs2022

      - name: Set up problem matching
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Build ${{matrix.configuration}}-binaries-bf2-rtx
        run: msbuild /m /v:minimal /p:Configuration=${{matrix.configuration}} /p:Platform=Win32 build/bf2-rtx.sln

      - name: Move build files 
        run: |
          move build/bin/${{matrix.configuration}}/bf2rtx.asi ./
          move build/bin/${{matrix.configuration}}/bf2rtx.pdb ./

      - name: Upload ${{matrix.configuration}}-binaries-bf2-rtx
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.configuration}}-binaries-bf2-rtx
          path: |
            ./bf2rtx.asi
            ./bf2rtx.pdb
            ./assets/